[package]
name = "jua"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusty-args = { git = "https://github.com/juliohq/rusty-args"}
